apiVersion: batch/v1
kind: CronJob
metadata:
  name: lululemon-stockchecker-cron
spec:
  # Cronjob will run every hour to check for product availability.
  schedule: '@hourly'
  # Keep all jobs from the last 24 hours
  successfulJobsHistoryLimit: 24
  failedJobsHistoryLimit: 24
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lululemon-stockchecker
            image: quay.io/cguertin14/lululemon-stockchecker
            env:
            # - name: LULULEMON_URI
            #   value: https://some-lululemon-product.com # TODO: change this value ;)
            # Warning: You need to define this secret in your config.
            - name: SLACK_WEBHOOK_URI
              valueFrom:
                secretKeyRef:
                  key: SLACK_WEBHOOK_URI
                  name: slack-webhook-uri
            - name: SMS_SENDER_PHONE_NUM
              valueFrom:
                secretKeyRef:
                  key: SMS_SENDER_PHONE_NUM
                  name: twilio-settings
            - name: SMS_RECIPIENT_PHONE_NUM
              valueFrom:
                secretKeyRef:
                  key: SMS_RECIPIENT_PHONE_NUM
                  name: twilio-settings
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  key: TWILIO_ACCOUNT_SID
                  name: twilio-settings
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TWILIO_AUTH_TOKEN
                  name: twilio-settings
            resources:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 250m
                memory: 128Mi
          restartPolicy: OnFailure
