apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lululemon-stockchecker

commonLabels:
  app.kubernetes.io/name: lululemon-stockchecker

resources:
- namespace.yml
- cronjob.yml
